[programs.devnet]
pro_gram = "EEs91kXyAGSMAajLKejmBeqxBxHEM7ZhZtGikwsNoEwa"
test_prog = "E69tkfspJSQJYBNXfk6wmVTtxVUvmtC1fdJwMSZuTejE"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/sayantank/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
